name: file_testkit
description: A simple way to mock file-related operations in Dart, ideal for testing.
version: 1.0.0
homepage: https://github.com/drown0315/file_testkit
issue_tracker: https://github.com/drown0315/file_testkit/issues

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  file: ^7.0.0

dev_dependencies:
  lints: ^3.0.0
  test: ^1.24.0
